PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX uo: <http://uniovi.es/miw/uo283069/entity/>
PREFIX uop: <http://uniovi.es/miw/uo283069/property/> 
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?subject ?subjectLabel ?predicate ?object
WHERE {
  ?subject a schema:Person .
  ?subject owl:sameAs ?wikidataEntity .
  SERVICE <https://query.wikidata.org/sparql> {
    ?wikidataEntity rdfs:label ?subjectLabel .
    ?wikidataEntity ?predicate ?object .
    FILTER (LANG(?subjectLabel) = "en")
  }
}