PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX ex: <http://example.org/>

SELECT ?object ?name ?subject
WHERE {
  ?object ex:references ?subject .
  ?object schema:name ?name . 
}